title = "Blades"
description = "Blazing fast dead simple static site generator"
keywords = "static site generator, fast, rust"
lang = "en-gb"
logo = "<span class=\"blades-logo\"></span>"

atom = false
rss = false

repository = "https://github.com/grego/blades"

footer = """
Created with **<span class="blades-logo"></span>blades**
(of course - check the [source](https://github.com/grego/bladesite))
by [Maro≈° Grego](https://grego.site).
No JavaScript used.
"""

[author]
name = "Maros Grego"

